name: CustomEnchants
version: '${version}'
main: dev.timca.customenchants.CustomEnchantsPlugin
api-version: '1.21'
description: Custom enchantments for Paper
bootstrapper: dev.timca.customenchants.CustomEnchantsBootstrapper